# Dockerfile

# Use an official node image as a parent image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Install serve to serve the build
RUN npm install -g serve

# Expose the port that the app runs on
EXPOSE 5173

# Start the app
CMD ["serve", "-s", "dist", "-l", "5173"]
